### ISSUE TITLE
Issue with downloads of releases

### ISSUE THREAD

**Issue by leonardoporpora** [copperhead/website-bugtracker#8]
If i try to download these links i have being asked of a username and passwd...
https://release.copperhead.co/taimen-factory-2018.05.08.01.tar.xz
https://release.copperhead.co/taimen-factory-2018.05.08.01.tar.xz.sig
https://release.copperhead.co/taimen-avb_pkmd.bin

**Comment by thestinger** [comment]
We do give the *sources* away for free based on the assumption that most people would much rather pay us for convenience than deal with the inconvenience involved in building each release.

**Comment by leonardoporpora** [comment]
So I have got a pixel 2 and I cannot install copperhead on it in any way?

**Comment by thestinger** [comment]
You can build it and install that.
